import { useState, useEffect, useCallback, useRef, useMemo, lazy, Suspense } from 'react'
import { MapPin, User, Users, Mail, Phone, Search, Loader2, AlertCircle, CheckCircle2, BarChart3, Building, FileText, Home, TrendingUp } from 'lucide-react'
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts'
import { useData } from '../hooks/useData'
import { useCouncilConfig } from '../context/CouncilConfig'
import { LoadingState } from '../components/ui'
import CollapsibleSection from '../components/CollapsibleSection'
import CouncillorLink from '../components/CouncillorLink'
import IntegrityBadge from '../components/IntegrityBadge'
import SparkLine from '../components/ui/SparkLine'
import GaugeChart from '../components/ui/GaugeChart'
import ChartCard from '../components/ui/ChartCard'
import { CHART_COLORS, TOOLTIP_STYLE, CHART_ANIMATION } from '../utils/constants'
import { slugify } from '../utils/format'
import '../components/ui/AdvancedCharts.css'
import './MyArea.css'

const WardMap = lazy(() => import('../components/WardMap'))

// Pure helper — no component deps, safe at module scope
const getDeprivationColor = (level) => {
  switch (level) {
    case 'Very High': return '#ff453a'
    case 'High': return '#ff6b35'
    case 'Medium-High': return '#ff9f0a'
    case 'Medium': return '#ffd60a'
    case 'Low': return '#30d158'
    case 'Very Low': return '#66d4cf'
    default: return '#86868b'
  }
}

function MyArea() {
  const config = useCouncilConfig()
  const councilName = config.council_name || 'Council'
  const { data, loading, error } = useData([
    '/data/wards.json',
    '/data/councillors.json',
    '/data/integrity.json',
  ])
  const [wards, councillors, integrityData] = data || [{}, [], null]
  // Deprivation is optional — LCC and other county councils don't have it
  const { data: deprivationRaw } = useData('/data/deprivation.json')
  const deprivation = deprivationRaw?.wards || {}
  // Property assets data (optional — only LCC has this currently)
  const { data: propertyRaw } = useData('/data/property_assets.json')
  const propertyAssets = propertyRaw?.assets || []
  // Planning data (optional — councils with planning ETL data)
  const { data: planningRaw } = useData('/data/planning.json')
  const planningData = planningRaw || null
  // HMO data (optional — councils with hmo ETL data)
  const { data: hmoRaw } = useData('/data/hmo.json')
  const hmoData = hmoRaw || null
  // Demographic fiscal data (optional — generated by ETL)
  const { data: demoFiscalRaw } = useData('/data/demographic_fiscal.json')
  // Ward boundaries for map (optional — not all councils have this)
  const { data: boundariesData } = useData(config.data_sources?.ward_boundaries ? '/data/ward_boundaries.json' : null)
  // Demographics data (optional — for ethnic composition pie chart)
  const { data: demographicsRaw } = useData(config.data_sources?.demographics ? '/data/demographics.json' : null)
  const demographicsWards = demographicsRaw?.wards || {}

  const wardMapData = useMemo(() => {
    if (!wards || typeof wards !== 'object') return {}
    const map = {}
    Object.entries(wards).forEach(([wardName, ward]) => {
      const councillors = ward.councillors || []
      const dep = deprivation[wardName]
      map[wardName] = {
        color: councillors[0]?.color || '#666',
        winner: councillors[0]?.party,
        partyColor: councillors[0]?.color || '#666',
        classLabel: dep?.deprivation_level ? `${dep.deprivation_level} deprivation` : null,
      }
    })
    return map
  }, [wards, deprivation])

  const [selectedWard, setSelectedWard] = useState(null)
  const [postcode, setPostcode] = useState('')
  const [postcodeLoading, setPostcodeLoading] = useState(false)
  const [postcodeError, setPostcodeError] = useState(null)
  const [postcodeResult, setPostcodeResult] = useState(null)
  const scrollTimerRef = useRef(null)

  // Cleanup scroll timer on unmount
  useEffect(() => {
    return () => { if (scrollTimerRef.current) clearTimeout(scrollTimerRef.current) }
  }, [])

  const lookupPostcode = useCallback(async (pc) => {
    const cleaned = pc.replace(/\s+/g, '').toUpperCase()
    if (cleaned.length < 5) {
      setPostcodeError('Please enter a valid postcode')
      return
    }

    setPostcodeLoading(true)
    setPostcodeError(null)
    setPostcodeResult(null)

    try {
      const res = await fetch(`https://api.postcodes.io/postcodes/${encodeURIComponent(cleaned)}`)
      const json = await res.json()

      if (json.status !== 200 || !json.result) {
        setPostcodeError('Postcode not found. Please check and try again.')
        return
      }

      const { admin_ward, admin_district } = json.result
      setPostcodeResult({ ward: admin_ward, district: admin_district, postcode: json.result.postcode })

      // Check if postcode is in this council area
      if (admin_district && admin_district.toLowerCase() !== councilName.toLowerCase()) {
        setPostcodeError(`That postcode is in ${admin_district}, not ${councilName}. Try a local postcode.`)
        return
      }

      // Try to match to ward data
      const wardMatch = Object.values(wards).find(w =>
        w.name.toLowerCase() === admin_ward?.toLowerCase()
      )

      if (wardMatch) {
        setSelectedWard(wardMatch.name)
        // Scroll to ward details
        if (scrollTimerRef.current) clearTimeout(scrollTimerRef.current)
        scrollTimerRef.current = setTimeout(() => {
          document.querySelector('.ward-details')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
        }, 100)
      } else {
        // Ward exists but not in our dataset — still show the info
        setPostcodeResult(prev => ({ ...prev, noData: true }))
      }
    } catch {
      setPostcodeError('Unable to look up postcode. Please try again.')
    } finally {
      setPostcodeLoading(false)
    }
  }, [wards, councilName])

  const handlePostcodeSubmit = (e) => {
    e.preventDefault()
    lookupPostcode(postcode)
  }

  useEffect(() => {
    document.title = `My Area | ${councilName} Council Transparency`
    return () => { document.title = `${councilName} Council Transparency` }
  }, [councilName])

  // === Advanced Visualization Data (computed before conditional returns) ===

  // Planning applications trend sparkline data — aggregate by year from applications
  const planningTrendData = useMemo(() => {
    if (!planningData?.summary?.by_year) return []
    const byYear = planningData.summary.by_year
    return Object.entries(byYear)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([, count]) => count)
  }, [planningData])

  // Ward-level planning trend — count applications per quarter from start_date
  const wardPlanningTrend = useMemo(() => {
    if (!selectedWard || !planningData?.applications) return []
    const wardApps = planningData.applications.filter(a => a.ward === selectedWard && a.start_date)
    if (wardApps.length < 3) return []
    // Group by quarter
    const quarters = {}
    wardApps.forEach(a => {
      const d = a.start_date.slice(0, 7) // YYYY-MM
      const qKey = d.slice(0, 4) + '-Q' + Math.ceil(parseInt(d.slice(5, 7)) / 3)
      quarters[qKey] = (quarters[qKey] || 0) + 1
    })
    return Object.entries(quarters)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([, count]) => count)
  }, [selectedWard, planningData])

  // HMO density sparkline — per-ward density values across all wards (context line)
  const hmoWardDensities = useMemo(() => {
    if (!hmoData?.summary?.by_ward) return []
    return Object.values(hmoData.summary.by_ward)
      .map(w => w.density_per_1000 || 0)
      .filter(d => d > 0)
      .sort((a, b) => a - b)
  }, [hmoData])

  // Ethnic composition pie chart data for selected ward
  const wardEthnicityData = useMemo(() => {
    if (!selectedWard || !demographicsWards[selectedWard]) return []
    const eth = demographicsWards[selectedWard].ethnicity || {}
    return Object.entries(eth)
      .filter(([k]) => !k.toLowerCase().includes('total') && !k.includes(': '))
      .map(([k, v]) => ({ name: k.split(',')[0].trim(), value: typeof v === 'object' ? (v.count || 0) : v }))
      .filter(e => e.value > 0)
      .sort((a, b) => b.value - a.value)
      .slice(0, 8)
  }, [selectedWard, demographicsWards])

  // Deprivation score for gauge chart
  const wardDeprivationScore = useMemo(() => {
    if (!selectedWard || !deprivation) return null
    const dep = deprivation[selectedWard] || Object.entries(deprivation).find(
      ([k]) => k.toLowerCase() === selectedWard.toLowerCase()
    )?.[1]
    if (!dep?.avg_imd_score) return null
    return dep.avg_imd_score
  }, [selectedWard, deprivation])

  if (loading) {
    return <LoadingState message="Loading ward data..." />
  }

  if (error) {
    return (
      <div className="page-error">
        <h2>Unable to load data</h2>
        <p>Please try refreshing the page.</p>
      </div>
    )
  }

  const wardList = Object.values(wards).sort((a, b) => a.name.localeCompare(b.name))

  const getDeprivationForWard = (wardName) => {
    if (!wardName || !deprivation) return null
    // Try exact match first, then case-insensitive
    return deprivation[wardName] || Object.entries(deprivation).find(
      ([k]) => k.toLowerCase() === wardName.toLowerCase()
    )?.[1] || null
  }

  const getWardCouncillors = (wardName) => {
    return councillors.filter(c => c.ward === wardName)
  }

  return (
    <div className="myarea-page animate-fade-in">
      <header className="page-header">
        <h1>My Area</h1>
        <p className="subtitle">
          Find your ward and councillors in {councilName}. Enter your postcode or select a ward below.
        </p>
      </header>

      {/* Postcode Lookup */}
      <section className="postcode-lookup">
        <form onSubmit={handlePostcodeSubmit} className="postcode-form" aria-label="Postcode lookup">
          <label htmlFor="postcode-input">Find your ward by postcode</label>
          <div className="postcode-input-row">
            <div className="postcode-input-wrapper">
              <Search size={18} className="postcode-search-icon" />
              <input
                id="postcode-input"
                type="text"
                placeholder="e.g. BB11 3DF"
                value={postcode}
                onChange={(e) => {
                  setPostcode(e.target.value)
                  setPostcodeError(null)
                  setPostcodeResult(null)
                }}
                maxLength={10}
                autoComplete="postal-code"
                aria-label="Enter your postcode"
              />
            </div>
            <button
              type="submit"
              className="postcode-btn"
              disabled={postcodeLoading || !postcode.trim()}
            >
              {postcodeLoading ? <Loader2 size={18} className="spin" /> : 'Look up'}
            </button>
          </div>
        </form>

        {postcodeError && (
          <div className="postcode-message error">
            <AlertCircle size={16} />
            <span>{postcodeError}</span>
          </div>
        )}

        {postcodeResult && !postcodeError && (
          <div className={`postcode-message ${postcodeResult.noData ? 'info' : 'success'}`}>
            {postcodeResult.noData ? (
              <>
                <AlertCircle size={16} />
                <span>Your ward is <strong>{postcodeResult.ward}</strong> in {postcodeResult.district}, but we don't have detailed councillor data for it yet.</span>
              </>
            ) : (
              <>
                <CheckCircle2 size={16} />
                <span><strong>{postcodeResult.postcode}</strong> is in <strong>{postcodeResult.ward}</strong> ward</span>
              </>
            )}
          </div>
        )}
      </section>

      {/* Ward Selector (dropdown) */}
      <section className="ward-selector">
        <label htmlFor="ward-select">Or select your ward:</label>
        <select
          id="ward-select"
          value={selectedWard || ''}
          onChange={(e) => setSelectedWard(e.target.value || null)}
        >
          <option value="">Choose a ward...</option>
          {wardList.map(ward => (
            <option key={ward.name} value={ward.name}>{ward.name}</option>
          ))}
        </select>
      </section>

      {/* Selected Ward Details */}
      {selectedWard && (
        <section className="ward-details animate-fade-in">
          <div className="ward-header">
            <MapPin size={24} className="ward-icon" />
            <div>
              <h2>{selectedWard}</h2>
              <p className="text-secondary">Your local councillors</p>
            </div>
          </div>

          {/* Ward Impact Statement — emotional narrative card */}
          {(() => {
            const depData = getDeprivationForWard(selectedWard)
            const wardCouncillors = getWardCouncillors(selectedWard)
            const wardIntegrity = integrityData?.councillors
              ? wardCouncillors.map(c => integrityData.councillors.find(ic => ic.name === c.name)).filter(Boolean)
              : []
            const flagged = wardIntegrity.filter(ic => (ic.total_flags || ic.flags || 0) > 0)
            const wardHmo = hmoData?.summary?.by_ward?.[selectedWard]
            const wardPlanning = planningData?.summary?.by_ward?.[selectedWard] || 0

            // Only show if we have at least deprivation data
            if (!depData && flagged.length === 0) return null

            return (
              <div className="deprivation-panel" style={{ marginTop: 0, borderLeft: '3px solid #12b6cf' }}>
                <h3 style={{ color: '#12b6cf' }}><AlertCircle size={16} /> What This Means For You</h3>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: 1.65, margin: '0.5rem 0' }}>
                  {depData && depData.national_percentile <= 20
                    ? `${selectedWard} ranks in the most deprived ${depData.national_percentile}% of wards in England (IMD score: ${depData.avg_imd_score}). That means residents here face harder pressures on income, employment, health and housing than most of the country — yet council spending decisions are made with almost no public scrutiny.`
                    : depData && depData.national_percentile <= 40
                    ? `${selectedWard} faces above-average deprivation (national percentile: ${depData.national_percentile}%, IMD score: ${depData.avg_imd_score}). Residents here deserve to know exactly where their council tax goes and whether it's being spent wisely.`
                    : depData
                    ? `${selectedWard} has an IMD score of ${depData.avg_imd_score} (national percentile: ${depData.national_percentile}%). Every ward deserves transparency about how public money is spent.`
                    : `Your ward deserves full transparency about how public money is spent on your behalf.`
                  }
                  {flagged.length > 0 && ` ${flagged.length} of your ${wardCouncillors.length} local councillor${wardCouncillors.length > 1 ? 's' : ''} ha${flagged.length > 1 ? 've' : 's'} integrity flags — check their profiles below.`}
                  {wardPlanning > 30 && ` There have been ${wardPlanning} planning applications in this area recently — is your neighbourhood changing faster than you think?`}
                  {wardHmo?.total > 10 && ` This ward has ${wardHmo.total} HMOs registered${wardHmo.density_per_1000 > 5 ? ` — a density of ${wardHmo.density_per_1000} per 1,000 people, well above average` : ''}.`}
                </p>
              </div>
            )
          })()}

          {(() => {
            const depData = getDeprivationForWard(selectedWard)
            if (!depData) return null
            const color = getDeprivationColor(depData.deprivation_level)
            return (
              <div className="deprivation-panel">
                <h3><BarChart3 size={16} /> Deprivation Index</h3>
                <div className="deprivation-stats">
                  <div className="dep-stat">
                    <span className="dep-badge" style={{ background: color + '20', color, borderColor: color }}>
                      {depData.deprivation_level}
                    </span>
                    <span className="dep-label">Deprivation Level</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{depData.avg_imd_score}</span>
                    <span className="dep-label">IMD Score</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{depData.avg_imd_decile}</span>
                    <span className="dep-label">Decile (1=most deprived)</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{depData.national_percentile ? `${depData.national_percentile}%` : '—'}</span>
                    <span className="dep-label">National Percentile</span>
                  </div>
                </div>
                <p className="dep-note">
                  Based on the English Indices of Deprivation 2019 (MHCLG). A score above 30 indicates significant deprivation.
                  Averaged across {depData.lsoa_count} small areas (LSOAs) in this ward.
                </p>
              </div>
            )
          })()}

          {/* Ward Demographic Pressure */}
          {(() => {
            if (!demoFiscalRaw?.pressure_zones) return null
            const wardZone = demoFiscalRaw.pressure_zones.find(z => z.ward === selectedWard)
            if (!wardZone && !demoFiscalRaw.fiscal_resilience_score) return null
            return (
              <div className="deprivation-panel" style={{ marginTop: '1rem' }}>
                <h3><Users size={16} /> Demographic Fiscal Pressure</h3>
                <div className="deprivation-stats">
                  <div className="dep-stat">
                    <span className="dep-value" style={{ color: demoFiscalRaw.fiscal_resilience_score < 30 ? '#ff453a' : demoFiscalRaw.fiscal_resilience_score < 50 ? '#ff9f0a' : '#30d158' }}>
                      {demoFiscalRaw.fiscal_resilience_score}/100
                    </span>
                    <span className="dep-label">Council Fiscal Score</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value" style={{ color: demoFiscalRaw.service_demand_pressure_score > 70 ? '#ff453a' : '#ff9f0a' }}>
                      {demoFiscalRaw.service_demand_pressure_score}/100
                    </span>
                    <span className="dep-label">Service Demand</span>
                  </div>
                  {wardZone && (
                    <>
                      <div className="dep-stat">
                        <span className="dep-value" style={{ color: wardZone.flag === 'CRITICAL' ? '#ff453a' : '#ff9f0a' }}>{wardZone.flag}</span>
                        <span className="dep-label">Ward Status</span>
                      </div>
                      {wardZone.muslim_pct > 0 && (
                        <div className="dep-stat">
                          <span className="dep-value">{wardZone.muslim_pct}%</span>
                          <span className="dep-label">Muslim Population</span>
                        </div>
                      )}
                    </>
                  )}
                </div>
                <p className="dep-note">
                  Fiscal analysis based on Census 2021 demographics, DfE SEND Statistics, and IMD 2019.
                  {wardZone ? ` ${selectedWard} is a pressure zone ward with ${wardZone.flag === 'CRITICAL' ? 'critical' : 'elevated'} demand.` : ''}
                </p>
              </div>
            )
          })()}

          {/* Property assets in this ward */}
          {(() => {
            const wardPropertyAssets = propertyAssets.filter(a =>
              a.ced === selectedWard || a.ward === selectedWard
            )
            if (wardPropertyAssets.length === 0) return null
            const totalSpend = wardPropertyAssets.reduce((s, a) => s + (a.linked_spend || 0), 0)
            const disposalCount = wardPropertyAssets.filter(a => a.disposal?.category === 'A' || a.disposal?.category === 'B').length
            const categories = {}
            wardPropertyAssets.forEach(a => { categories[a.category || 'other'] = (categories[a.category || 'other'] || 0) + 1 })
            return (
              <div className="deprivation-panel" style={{ marginTop: '1rem' }}>
                <h3><Building size={16} /> LCC Property Assets</h3>
                <div className="deprivation-stats">
                  <div className="dep-stat">
                    <span className="dep-value">{wardPropertyAssets.length}</span>
                    <span className="dep-label">Assets in Area</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{totalSpend > 0 ? `£${Math.round(totalSpend / 1000)}k` : '—'}</span>
                    <span className="dep-label">Linked Spend</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{disposalCount}</span>
                    <span className="dep-label">Disposal Candidates</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{Object.keys(categories).length}</span>
                    <span className="dep-label">Categories</span>
                  </div>
                </div>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.25rem', margin: '0.75rem 0' }}>
                  {Object.entries(categories).sort((a, b) => b[1] - a[1]).map(([cat, count]) => (
                    <span key={cat} style={{ fontSize: '0.7rem', background: 'rgba(255,255,255,0.06)', padding: '2px 8px', borderRadius: '4px' }}>
                      {cat.replace(/_/g, ' ')} ({count})
                    </span>
                  ))}
                </div>
                <a href="/properties" style={{ color: 'var(--accent-primary, #12B6CF)', fontSize: '0.8rem' }}>
                  View all assets →
                </a>
              </div>
            )
          })()}

          {/* Planning activity in this ward */}
          {(() => {
            if (!planningData?.summary?.by_ward) return null
            const wardApps = planningData.summary.by_ward[selectedWard] || 0
            if (wardApps === 0) return null
            const totalApps = planningData.summary.total || 1
            const wardPct = Math.round((wardApps / totalApps) * 100)
            const approvalRate = planningData.summary.approval_rate
            const efficiency = planningData.efficiency
            // Get recent applications for this ward
            const wardRecent = (planningData.applications || [])
              .filter(a => a.ward === selectedWard)
              .sort((a, b) => (b.start_date || '').localeCompare(a.start_date || ''))
              .slice(0, 5)
            return (
              <div className="deprivation-panel" style={{ marginTop: '1rem' }}>
                <h3><FileText size={16} /> Planning Activity</h3>
                <div className="deprivation-stats">
                  <div className="dep-stat">
                    <span className="dep-value">{wardApps.toLocaleString()}</span>
                    <span className="dep-label">Applications ({wardPct}% of total)</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{approvalRate != null ? `${Math.round(approvalRate * 100)}%` : '—'}</span>
                    <span className="dep-label">Council Approval Rate</span>
                  </div>
                  <div className="dep-stat">
                    <span className="dep-value">{planningData.summary.avg_decision_days || '—'}</span>
                    <span className="dep-label">Avg Days to Decision</span>
                  </div>
                  {efficiency?.cost_per_application > 0 && (
                    <div className="dep-stat">
                      <span className="dep-value">£{efficiency.cost_per_application.toLocaleString()}</span>
                      <span className="dep-label">Cost per App ({efficiency.budget_year})</span>
                    </div>
                  )}
                </div>
                {wardRecent.length > 0 && (
                  <div style={{ marginTop: '0.75rem' }}>
                    <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Recent applications:</p>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
                      {wardRecent.map((app, i) => (
                        <div key={app.uid || i} style={{ fontSize: '0.7rem', background: 'rgba(255,255,255,0.04)', padding: '0.35rem 0.5rem', borderRadius: '4px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '0.5rem' }}>
                          <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{app.description || app.address}</span>
                          <span style={{ flexShrink: 0, color: app.state?.includes('Approved') || app.state?.includes('Granted') ? '#30d158' : app.state?.includes('Refused') || app.state?.includes('Rejected') ? '#ff453a' : 'var(--text-secondary)', fontSize: '0.65rem' }}>
                            {app.state || 'Pending'}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                <p className="dep-note">
                  Source: PlanIt planning portal. {planningData.meta?.years_back || 3}-year history.
                </p>
              </div>
            )
          })()}

          {/* HMO data for this ward */}
          {(() => {
            if (!hmoData?.summary?.by_ward) return null
            const wardHmo = hmoData.summary.by_ward[selectedWard]
            if (!wardHmo || wardHmo.total === 0) return null
            return (
              <div className="deprivation-panel" style={{ marginTop: '1rem' }}>
                <h3><Home size={16} /> Houses in Multiple Occupation</h3>
                <div className="deprivation-stats">
                  {wardHmo.licensed_hmos > 0 && (
                    <div className="dep-stat">
                      <span className="dep-value">{wardHmo.licensed_hmos}</span>
                      <span className="dep-label">Licensed HMOs</span>
                    </div>
                  )}
                  {wardHmo.planning_applications > 0 && (
                    <div className="dep-stat">
                      <span className="dep-value">{wardHmo.planning_applications}</span>
                      <span className="dep-label">HMO Planning Apps</span>
                    </div>
                  )}
                  {wardHmo.density_per_1000 > 0 && (
                    <div className="dep-stat">
                      <span className="dep-value" style={{ color: wardHmo.density_per_1000 > 5 ? '#ff453a' : wardHmo.density_per_1000 > 2 ? '#ff9500' : '#30d158' }}>
                        {wardHmo.density_per_1000}
                      </span>
                      <span className="dep-label">HMOs per 1,000 pop</span>
                    </div>
                  )}
                  {wardHmo.population > 0 && (
                    <div className="dep-stat">
                      <span className="dep-value">{wardHmo.population.toLocaleString()}</span>
                      <span className="dep-label">Ward Population</span>
                    </div>
                  )}
                </div>
                <p className="dep-note">
                  Source: {hmoData.meta?.register_name || 'Council HMO register'}.
                  {hmoData.meta?.coverage === 'planning_only' ? ' Planning applications only — register data via FOI.' : ''}
                  {hmoData.summary?.total_bed_spaces > 0 ? ` ${hmoData.summary.total_bed_spaces.toLocaleString()} bed spaces across ${hmoData.summary.total_licensed} licensed HMOs district-wide.` : ''}
                </p>
              </div>
            )
          })()}

          <div className="ward-councillors">
            {getWardCouncillors(selectedWard).map(councillor => (
              <div key={councillor.id} className="councillor-detail-card">
                <div
                  className="party-bar"
                  style={{ background: councillor.party_color }}
                />
                <div className="councillor-content">
                  <div className="councillor-main">
                    <User size={40} className="councillor-avatar" />
                    <div>
                      <h3>
                        <CouncillorLink
                          name={councillor.name}
                          councillorId={councillor.id || slugify(councillor.name)}
                          integrityData={integrityData}
                        />
                      </h3>
                      <span
                        className="party-badge"
                        style={{
                          background: councillor.party_color + '25',
                          color: councillor.party_color
                        }}
                      >
                        {councillor.party}
                      </span>
                    </div>
                  </div>

                  {councillor.roles?.length > 0 && (
                    <div className="councillor-roles">
                      {councillor.roles.map((role, i) => (
                        <span key={i} className="role-badge">{role}</span>
                      ))}
                    </div>
                  )}

                  <div className="councillor-contact">
                    {councillor.email && (
                      <a href={`mailto:${councillor.email}`} className="contact-link">
                        <Mail size={16} />
                        <span>{councillor.email}</span>
                      </a>
                    )}
                    {councillor.phone && (
                      <a href={`tel:${councillor.phone}`} className="contact-link">
                        <Phone size={16} />
                        <span>{councillor.phone}</span>
                      </a>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* ===== WARD DASHBOARD VISUALISATIONS ===== */}
      {selectedWard && (wardPlanningTrend.length > 0 || hmoWardDensities.length > 0 || wardEthnicityData.length > 0 || wardDeprivationScore != null) && (
        <section className="ward-dashboard animate-fade-in" aria-label="Ward data visualisations">
          <h2 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: 8, color: '#fff' }}>
            <TrendingUp size={20} style={{ color: '#00d4aa' }} />
            {selectedWard} — Data Dashboard
          </h2>

          <div className="ward-dashboard-grid" style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
            gap: '1rem',
            marginBottom: '1.5rem',
          }}>

            {/* SparkLine: Planning Applications Trend */}
            {wardPlanningTrend.length >= 3 && (
              <div className="ward-dash-card" style={{
                background: 'rgba(28,28,30,0.7)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255,255,255,0.06)',
                borderRadius: 12,
                padding: '1rem 1.25rem',
              }}>
                <div style={{ fontSize: '0.75rem', color: '#8e8e93', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  Planning Applications
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <SparkLine
                    data={wardPlanningTrend}
                    color="#00d4aa"
                    width={120}
                    height={32}
                    fill
                    showDot
                    trend
                  />
                  <div>
                    <div style={{ fontSize: '1.25rem', fontWeight: 700, color: '#fff' }}>
                      {wardPlanningTrend[wardPlanningTrend.length - 1]}
                    </div>
                    <div style={{ fontSize: '0.65rem', color: '#8e8e93' }}>latest quarter</div>
                  </div>
                </div>
                <div style={{ fontSize: '0.65rem', color: '#636366', marginTop: 6 }}>
                  {wardPlanningTrend.length} quarters tracked
                </div>
              </div>
            )}

            {/* SparkLine: HMO Density Context */}
            {hmoWardDensities.length >= 3 && (() => {
              const wardHmo = hmoData?.summary?.by_ward?.[selectedWard]
              if (!wardHmo || !wardHmo.density_per_1000) return null
              const wardDensity = wardHmo.density_per_1000
              const rank = hmoWardDensities.filter(d => d <= wardDensity).length
              const pctRank = Math.round((rank / hmoWardDensities.length) * 100)
              return (
                <div className="ward-dash-card" style={{
                  background: 'rgba(28,28,30,0.7)',
                  backdropFilter: 'blur(20px)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  borderRadius: 12,
                  padding: '1rem 1.25rem',
                }}>
                  <div style={{ fontSize: '0.75rem', color: '#8e8e93', fontWeight: 600, marginBottom: 8, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                    HMO Density
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <SparkLine
                      data={hmoWardDensities}
                      color={wardDensity > 5 ? '#ff453a' : '#ff9f0a'}
                      width={120}
                      height={32}
                      fill
                      showDot
                      showMinMax
                    />
                    <div>
                      <div style={{ fontSize: '1.25rem', fontWeight: 700, color: wardDensity > 5 ? '#ff453a' : wardDensity > 2 ? '#ff9f0a' : '#30d158' }}>
                        {wardDensity}
                      </div>
                      <div style={{ fontSize: '0.65rem', color: '#8e8e93' }}>per 1,000 pop</div>
                    </div>
                  </div>
                  <div style={{ fontSize: '0.65rem', color: '#636366', marginTop: 6 }}>
                    {pctRank}th percentile across {hmoWardDensities.length} wards
                  </div>
                </div>
              )
            })()}

            {/* GaugeChart: Deprivation Score */}
            {wardDeprivationScore != null && (
              <div className="ward-dash-card" style={{
                background: 'rgba(28,28,30,0.7)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255,255,255,0.06)',
                borderRadius: 12,
                padding: '1rem 1.25rem',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
              }}>
                <div style={{ fontSize: '0.75rem', color: '#8e8e93', fontWeight: 600, marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.5px', alignSelf: 'flex-start' }}>
                  Deprivation Score
                </div>
                <GaugeChart
                  value={wardDeprivationScore}
                  max={100}
                  label="IMD Score"
                  subtitle={wardDeprivationScore > 30 ? 'Above national threshold' : 'Below national threshold'}
                  size={150}
                  thickness={10}
                />
              </div>
            )}

            {/* PieChart: Ethnic Composition */}
            {wardEthnicityData.length > 0 && (
              <div className="ward-dash-card" style={{
                background: 'rgba(28,28,30,0.7)',
                backdropFilter: 'blur(20px)',
                border: '1px solid rgba(255,255,255,0.06)',
                borderRadius: 12,
                padding: '1rem 1.25rem',
              }}>
                <div style={{ fontSize: '0.75rem', color: '#8e8e93', fontWeight: 600, marginBottom: 4, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  Ethnic Composition
                </div>
                <ResponsiveContainer width="100%" height={160}>
                  <PieChart>
                    <Pie
                      data={wardEthnicityData}
                      dataKey="value"
                      nameKey="name"
                      cx="50%"
                      cy="50%"
                      innerRadius={35}
                      outerRadius={60}
                      paddingAngle={2}
                      animationDuration={CHART_ANIMATION.duration}
                    >
                      {wardEthnicityData.map((_, i) => (
                        <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip
                      contentStyle={TOOLTIP_STYLE}
                      formatter={(v, name) => {
                        const total = wardEthnicityData.reduce((s, e) => s + e.value, 0)
                        const pct = total > 0 ? ((v / total) * 100).toFixed(1) : 0
                        return [`${v.toLocaleString()} (${pct}%)`, name]
                      }}
                    />
                  </PieChart>
                </ResponsiveContainer>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.3rem', marginTop: 4 }}>
                  {wardEthnicityData.slice(0, 5).map((e, i) => (
                    <span key={e.name} style={{
                      fontSize: '0.6rem',
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: 3,
                      color: '#8e8e93',
                    }}>
                      <span style={{
                        width: 6,
                        height: 6,
                        borderRadius: '50%',
                        background: CHART_COLORS[i % CHART_COLORS.length],
                        display: 'inline-block',
                        flexShrink: 0,
                      }} />
                      {e.name}
                    </span>
                  ))}
                </div>
              </div>
            )}

          </div>
        </section>
      )}

      {/* ===== WARD MAP ===== */}
      {boundariesData?.features?.length > 0 && Object.keys(wardMapData).length > 0 && (
        <CollapsibleSection title="Ward Map" icon={<MapPin size={18} />} defaultOpen subtitle="Click a ward to see your councillors and local data. Coloured by party control." id="ward-map">
          <div className="premium-map-section">
            <div className="premium-map-3d">
              <div className="premium-map-orb premium-map-orb--red" />
              <div className="premium-map-orb premium-map-orb--blue" />
              <div className="premium-map-frame premium-map-frame--compact">
                <Suspense fallback={<div className="premium-map-loading">Loading map...</div>}>
                  <WardMap
                    boundaries={boundariesData}
                    wardData={wardMapData}
                    wardsUp={Object.keys(wardMapData)}
                    overlayMode="party"
                    selectedWard={selectedWard}
                    onWardClick={(name) => {
                      setSelectedWard(name)
                      setTimeout(() => {
                        document.querySelector('.ward-details')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
                      }, 100)
                    }}
                    height="420px"
                  />
                </Suspense>
              </div>
            </div>
          </div>
        </CollapsibleSection>
      )}

      {/* All Wards Grid */}
      <CollapsibleSection title="All Wards" icon={<Users size={18} />} defaultOpen count={wardList.length} countLabel="wards" id="all-wards">
        <div className="wards-grid">
          {wardList.map(ward => {
            const wardCouncillors = getWardCouncillors(ward.name)
            const wardDep = getDeprivationForWard(ward.name)
            const wardPlanningApps = planningData?.summary?.by_ward?.[ward.name] || 0
            const wardHmoCount = hmoData?.summary?.by_ward?.[ward.name]?.total || 0

            return (
              <div
                key={ward.name}
                className={`ward-card ${selectedWard === ward.name ? 'selected' : ''}`}
                role="button"
                tabIndex={0}
                aria-pressed={selectedWard === ward.name}
                onClick={() => setSelectedWard(ward.name)}
                onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); setSelectedWard(ward.name) } }}
              >
                <div
                  className="ward-party-indicator"
                  style={{ background: ward.color }}
                />
                <div className="ward-content">
                  <h3>{ward.name}</h3>
                  <p className="ward-parties text-secondary">
                    {ward.parties?.join(', ')}
                  </p>
                  <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap' }}>
                    {wardDep && (
                      <span
                        className="ward-dep-badge"
                        style={{
                          background: getDeprivationColor(wardDep.deprivation_level) + '20',
                          color: getDeprivationColor(wardDep.deprivation_level),
                          borderColor: getDeprivationColor(wardDep.deprivation_level),
                        }}
                      >
                        {wardDep.deprivation_level} deprivation
                      </span>
                    )}
                    {wardPlanningApps > 0 && (
                      <span
                        className="ward-dep-badge"
                        style={{
                          background: wardPlanningApps > 50 ? 'rgba(255,149,0,0.15)' : 'rgba(48,209,88,0.15)',
                          color: wardPlanningApps > 50 ? '#ff9500' : '#30d158',
                          borderColor: wardPlanningApps > 50 ? '#ff9500' : '#30d158',
                        }}
                      >
                        {wardPlanningApps} planning apps
                      </span>
                    )}
                    {wardHmoCount > 0 && (
                      <span
                        className="ward-dep-badge"
                        style={{
                          background: wardHmoCount > 20 ? 'rgba(255,69,58,0.15)' : wardHmoCount > 5 ? 'rgba(255,149,0,0.15)' : 'rgba(175,130,255,0.15)',
                          color: wardHmoCount > 20 ? '#ff453a' : wardHmoCount > 5 ? '#ff9500' : '#af82ff',
                          borderColor: wardHmoCount > 20 ? '#ff453a' : wardHmoCount > 5 ? '#ff9500' : '#af82ff',
                        }}
                      >
                        {wardHmoCount} HMOs
                      </span>
                    )}
                  </div>
                  <div className="ward-councillor-names">
                    {wardCouncillors.map(c => (
                      <span key={c.id} className="councillor-name">
                        <CouncillorLink name={c.name} councillorId={c.id || slugify(c.name)} compact />
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </CollapsibleSection>

      {/* Official Council Link */}
      <CollapsibleSection title="More Information" icon={<AlertCircle size={18} />} id="more-info">
        <div className="find-ward-card">
          <p>
            For full councillor details and meeting schedules, visit the official {councilName} Council website.
          </p>
          <a
            href={config.find_councillor_url || `${config.official_website || '#'}/council-democracy/councillors-mps/find-your-councillor/`}
            target="_blank"
            rel="noopener noreferrer"
            className="find-ward-link"
          >
            Find Your Councillor on {(config.official_website || '').replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '')} →
          </a>
        </div>
      </CollapsibleSection>
    </div>
  )
}

export default MyArea
